In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10, 30, (3,2,3))
print(arr)

[[[16 20 28]
  [20 28 27]]

 [[12 21 10]
  [12 19 10]]

 [[20 14 29]
  [15 24 28]]]


In [3]:
print(arr.shape)
print(arr.size)

(3, 2, 3)
18


In [22]:
arr[::1]

array([[[16, 20, 28],
        [20, 28, 27]],

       [[12, 21, 10],
        [12, 19, 10]],

       [[20, 14, 29],
        [15, 24, 28]]])

In [26]:
arr[::2, ::1, ::2]

array([[[16, 28],
        [20, 27]],

       [[20, 29],
        [15, 28]]])

####Array creation method
    np.array(seq)
    np.arange(start, end, step)
    np.linspace(start,end, n)
    np.random.randint(start, end, n)

array re_shape

In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(a)
print(a.shape)
a.reshape((4,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
a.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
b = a.reshape(2, 6)
# view of original array if any change is made in b then the change will be made in the original array
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [44]:
# we can use the copy function if we don't want any other variable to change the original array
c = a.reshape(2, 6).copy()
c[0, 0] = 100
print(c)
print(a)  # will not change in the original array i.e array a

[[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [45]:
a = a.reshape(-1, 4)  # py automatically calculates the total no of rows if there needs to be 4 cols
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
a = a.reshape(6, -1)  # py automatically calculates the total no of cols of there were 6 rows
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [52]:
a = a.reshape(3, 2, 2)
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [53]:
a = a.flatten()  # flatten function converts the array into 1d array from 3d or 2d array
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### conversion of 1d array to 2d array using the same 1d array

In [54]:
arr1 = a[np.newaxis, :]  # adds a new row by reading the col value
print(arr1)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [55]:
arr2 = a[:, np.newaxis]  # adds a new col by reading the row value
print(arr2)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [56]:
a = a.reshape(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [62]:
a[np.newaxis, :, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [63]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

the difference between the flatten fucntion and the ravel function is 
flatten always produces the copy of the array
where as the ravel function tries to return the original view of the array

In [65]:
a.dtype  # prints the type of the array

dtype('int32')

In [66]:
a.astype(np.float)

C:\Users\mdadn\AppData\Local\Temp\ipykernel_18564\2714328292.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a.astype(np.float)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [67]:
new_arr = a.astype(np.int16)

In [71]:
z = np.array([1, 2, 3, 4, 5, 6], dtype=float)
print(z)  # float values will be printed

[1. 2. 3. 4. 5. 6.]


In [68]:
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int16)

astype(np.int16) is used to change the dtype of the array into some another value

In [72]:
z.dtype

dtype('float64')

In [73]:
k = a.astype(int)

In [74]:
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
p = np.array([566, 3, 80, 290, 30, 50])

In [76]:
p.dtype

dtype('int32')

The default size of each element in the array is 32 bits singned which means values can range from -2**32 to +2**32.

In [78]:
x = p.astype(np.uint8)

In [79]:
x

array([54,  3, 80, 34, 30, 50], dtype=uint8)

In [81]:
res = np.zeros(10)  # np.zeros(10) creates a array with 10 elements and each element is initialized to 0
print(res)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
res1  = np.zeros((4,5))  # shape of the array can also be passed as an argument in zeros function
print(res1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [86]:
res2 = np.ones((2,3,4))  # similar to zeros ones array can also be created 
print(res2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


####identity matrix / eye matrix
        except diagonal all the other elements are zero
        A.Indentity Matrix = A

In [88]:
a = np.random.randint(10, 30,(5, 4))
print(a)

[[17 17 28 25]
 [17 22 19 11]
 [16 27 27 20]
 [17 11 18 18]
 [26 22 29 16]]


####matix multiplication
mxn and nxk will give mxk matrix

In [90]:
i = np.eye(4)
print(i)
print(i.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [91]:
a.dot(i)  #a.dot(i) gives the matrix multiplication with a and i

array([[17., 17., 28., 25.],
       [17., 22., 19., 11.],
       [16., 27., 27., 20.],
       [17., 11., 18., 18.],
       [26., 22., 29., 16.]])

###Array Operation

In [96]:
a = np.array([4, 3, 6, 2])

In [97]:
a + 2

array([6, 5, 8, 4])

In [98]:
a * 2

array([ 8,  6, 12,  4])

In [99]:
a ** 2

array([16,  9, 36,  4])

In [100]:
b = np.array([1, 2, 3, 4])

In [101]:
a + b

array([5, 5, 9, 6])

In [102]:
a * b  # this is scalar multilication(element wise multiplication)

array([ 4,  6, 18,  8])

In [103]:
a / b

array([4. , 1.5, 2. , 0.5])

In [104]:
a**b  

array([  4,   9, 216,  16])

In [105]:
np.multiply(a, b)

array([ 4,  6, 18,  8])

In [108]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])

In [109]:
np.multiply(A, B)  # this is also matrix multiplication

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [110]:
A*B

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [111]:
A @ B  # this is matrix multiplication

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

 for any element wise operation the shape of arrays among which operation is going to take place should be same
 for matrix multiplication no of cols in the first array should be equal to the no of rows in the second array

Transpose of a matrix
$A^2 = A.A^T$

In [113]:
arr_t = A.T  # A.T is used to transpose any of the 2d array
print(arr_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [114]:
sqr_A = A@arr_t  # simply using the formula for calculating the square of a matrix
print(sqr_A)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [115]:
np.transpose(sqr_A)  # np.transpose(arr) can also be used to find the transpose of array

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

Stats

In [117]:
a = np.array([4, 5, 6, 7, 8, 4, 6, 7])

In [118]:
a

array([4, 5, 6, 7, 8, 4, 6, 7])

In [119]:
np.mean(a)

5.875

In [120]:
np.median(a)

6.0

In [121]:
Q1, Q2, Q3 = np.quantile(a, [0.25, 0.5, 0.75])
print(Q1)
print(Q2)
print(Q3)

4.75
6.0
7.0


In [122]:
np.var(a)  # calculation of variance using np.var(array) function

1.859375

In [123]:
np.std(a)  # calculation of standard deviation using np.std(array) function

1.3635890143294642

Applying these functions on 2d Array

In [124]:
arr = np.random.randint(1, 10,(5, 4))

In [125]:
arr

array([[7, 6, 1, 5],
       [7, 5, 1, 2],
       [5, 8, 3, 8],
       [3, 6, 2, 6],
       [2, 2, 1, 7]])

In [126]:
np.mean(arr)

4.35

The np.mean(arr) can give the mean  of row or col or the entire 2d array.
The default behaviour of the np.mean(array) is it's gives the mean of entire array

In [127]:
np.sum(arr)  # gives the sum of entire array

87

In [128]:
np.sum(arr) / arr.size  # avg same as np.mean(array)

4.35

How to calculate the average of each row

axis0 does col wise operations
axis1 does row wise operations 
(**remember**)

Row wise mean value

In [129]:
np.mean(arr, axis = 1)  # 5 values will be printed beacause there are 5 rows

array([4.75, 3.75, 6.  , 4.25, 3.  ])

Col wise mean value

In [130]:
np.mean(arr, axis = 0)  # 4 rows will be printed because there are 4 cols

array([4.8, 5.4, 1.6, 5.6])

row wise standard deviation calculation 

In [131]:
np.std(arr, axis=1)

array([2.27760839, 2.384848  , 2.12132034, 1.78535711, 2.34520788])

col wise starndard deviation calculation

In [132]:
np.std(arr, axis=0)

array([2.03960781, 1.95959179, 0.8       , 2.05912603])

quantile calculation on col

In [133]:
np.quantile(arr, [0.25, 0.5, 0.75], axis = 0)

array([[3., 5., 1., 5.],
       [5., 6., 1., 6.],
       [7., 6., 2., 7.]])