In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30])
print(a)

[10 20 30]


In [3]:
b = np.array([[50, 105, 150], 
             [10, 20, 170]])
print(b)

[[ 50 105 150]
 [ 10  20 170]]


####how to create array
1. using python sequential data types

In [4]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a.size

4

In [6]:
a.shape  # arrangement of data according to dimension 

(4,)

In [7]:
a.itemsize  # size of each element in the array in bytes

4

In [8]:
a.dtype

dtype('int32')

In [9]:
(999999999999999999999999999999999999999999999999).bit_length()

160

In [11]:
a = np.array([1, 2, 3, 4, 5, 7, 99999999999999999999999999999999999999999999999999])

In [12]:
arr = np.arange(5, 55, 5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [16]:
# a=arr.np(10, 2) ## this will give error
a=np.arange(10, 2, -1)
print(a)

[10  9  8  7  6  5  4  3]


In [19]:
num = int(input("number: "))
num = np.arange(num, num*11, num)
print(num)

number: 5
[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
import matplotlib.pyplot as plt
month = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
company1 = [ 40 , 60, 50, 40, 70, 80, 90, 40, 50, 56, 76, 40]
company2 = [23, 45 , 67, 21, 32, 45,67, 89, 90, 21, 32, 33, 10]
plt.plot(month, company1)
plt.plot(month, company2)
plt.show()