In [1]:
import numpy as np
arr = np.array([1, 5, 67, 8, 9, ])

In [2]:
arr.sort()  # inplace sorting

In [3]:
print(arr)

[ 1  5  8  9 67]


In [4]:
weight = np.random.randint(1500, 2500, 10)
mpg = np.random.randint(5, 30, 10)

In [5]:
weight

array([2316, 1933, 1860, 2276, 2210, 2498, 2202, 1826, 2016, 1506])

In [6]:
mpg

array([ 6,  6, 11,  8, 23,  8,  7,  8, 29, 25])

#### if we use sort method to sort the array using arr.sort() function then the original array will be altered and  then the correspoding mpg will not be correct

sorted indexes which represents sorted array can be done using:- 'np.argsort(arr)'

In [7]:
np.min(weight)

1506

In [8]:
np.min(mpg)

6

In [9]:
np.max(mpg)

29

In [10]:
weight [mpg == np.max(mpg)]  # weight of car with max milege

array([2016])

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a ** 2
print(a)
print(b)
print(np.append(a, b))  # merge a and b 

[1 2 3 4 5 6]
[ 1  4  9 16 25 36]
[ 1  2  3  4  5  6  1  4  9 16 25 36]


 a(arr) needs to get converted into 2D array such that it has one col and 6 row
 b(arr) needs to get converted into 2D array such that it has one col and 6 row

In [12]:
a.reshape(-1, 1)  # -1 because row is not known

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
b.reshape(-1, 1)

array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36]])

  'np.h/vstack((a1, a2, a3, a4,......))' - to combine two more arrays horizontally or column wise/vertical or row wise
  similar methods are:-
  np.c_/r_[a1, a2, a3,......]
  np.concatenate((a1, a2, a3,....) axis=0/1)

if we are combining row wise total no of cols should be same
and of we are combining col wise total no of rows should be same

In [14]:
x = np.random.randint(1, 10, (5, 3))
y = np.random.randint(1, 10, (5, 6))
z = np.random.randint(1, 10, (5, 4))

In [15]:
print(x)
print(y)
print(z)

[[3 9 6]
 [3 9 1]
 [1 1 6]
 [7 8 3]
 [6 6 8]]
[[4 5 9 3 5 5]
 [8 2 1 9 7 2]
 [4 7 5 5 9 7]
 [6 8 8 4 6 4]
 [2 8 6 7 9 8]]
[[8 6 3 4]
 [2 6 2 8]
 [2 1 4 4]
 [2 3 6 1]
 [6 7 5 7]]


In [16]:
r = np.hstack((x, y, z))  # col wise concatenation 
r

array([[3, 9, 6, 4, 5, 9, 3, 5, 5, 8, 6, 3, 4],
       [3, 9, 1, 8, 2, 1, 9, 7, 2, 2, 6, 2, 8],
       [1, 1, 6, 4, 7, 5, 5, 9, 7, 2, 1, 4, 4],
       [7, 8, 3, 6, 8, 8, 4, 6, 4, 2, 3, 6, 1],
       [6, 6, 8, 2, 8, 6, 7, 9, 8, 6, 7, 5, 7]])

In [17]:
r = np.c_[x, y, z]  # another way to combine all the cols
r

array([[3, 9, 6, 4, 5, 9, 3, 5, 5, 8, 6, 3, 4],
       [3, 9, 1, 8, 2, 1, 9, 7, 2, 2, 6, 2, 8],
       [1, 1, 6, 4, 7, 5, 5, 9, 7, 2, 1, 4, 4],
       [7, 8, 3, 6, 8, 8, 4, 6, 4, 2, 3, 6, 1],
       [6, 6, 8, 2, 8, 6, 7, 9, 8, 6, 7, 5, 7]])

In [18]:
r = np.concatenate((x, y, z), axis = 1)  # we can combine horizontally and vertically both by providing thr axis
r

array([[3, 9, 6, 4, 5, 9, 3, 5, 5, 8, 6, 3, 4],
       [3, 9, 1, 8, 2, 1, 9, 7, 2, 2, 6, 2, 8],
       [1, 1, 6, 4, 7, 5, 5, 9, 7, 2, 1, 4, 4],
       [7, 8, 3, 6, 8, 8, 4, 6, 4, 2, 3, 6, 1],
       [6, 6, 8, 2, 8, 6, 7, 9, 8, 6, 7, 5, 7]])

In [19]:
z = np.random.randint(1, 20, (3, 3))
k = np.random.randint(1, 10, (5, 3))
p = np.random.randint(1, 20, (2, 3))

In [20]:
print(z)
print(k)
print(p)

[[17  2  4]
 [ 4 18 19]
 [ 1  4  7]]
[[1 2 6]
 [8 6 7]
 [4 8 1]
 [9 5 7]
 [2 2 4]]
[[ 1  1 11]
 [ 3  5  3]]


In [21]:
r = np.vstack((z, k, p))
r

array([[17,  2,  4],
       [ 4, 18, 19],
       [ 1,  4,  7],
       [ 1,  2,  6],
       [ 8,  6,  7],
       [ 4,  8,  1],
       [ 9,  5,  7],
       [ 2,  2,  4],
       [ 1,  1, 11],
       [ 3,  5,  3]])

In [22]:
r = np.r_[z, k, p]
r

array([[17,  2,  4],
       [ 4, 18, 19],
       [ 1,  4,  7],
       [ 1,  2,  6],
       [ 8,  6,  7],
       [ 4,  8,  1],
       [ 9,  5,  7],
       [ 2,  2,  4],
       [ 1,  1, 11],
       [ 3,  5,  3]])

In [23]:
r = np.concatenate((z, k, p), axis=0)
r

array([[17,  2,  4],
       [ 4, 18, 19],
       [ 1,  4,  7],
       [ 1,  2,  6],
       [ 8,  6,  7],
       [ 4,  8,  1],
       [ 9,  5,  7],
       [ 2,  2,  4],
       [ 1,  1, 11],
       [ 3,  5,  3]])

In [24]:
weight

array([2316, 1933, 1860, 2276, 2210, 2498, 2202, 1826, 2016, 1506])

In [25]:
mpg

array([ 6,  6, 11,  8, 23,  8,  7,  8, 29, 25])

In [26]:
r = np.vstack((weight, mpg))
r

array([[2316, 1933, 1860, 2276, 2210, 2498, 2202, 1826, 2016, 1506],
       [   6,    6,   11,    8,   23,    8,    7,    8,   29,   25]])

In [27]:
new_arr = np.concatenate((weight.reshape(-1, 1), mpg.reshape(-1, 1)), axis = 1)
new_arr

array([[2316,    6],
       [1933,    6],
       [1860,   11],
       [2276,    8],
       [2210,   23],
       [2498,    8],
       [2202,    7],
       [1826,    8],
       [2016,   29],
       [1506,   25]])

In [28]:
new_arr.sort(axis = 0)  # the corresponding values are changed so this method can't be used for sorting
new_arr

array([[1506,    6],
       [1826,    6],
       [1860,    7],
       [1933,    8],
       [2016,    8],
       [2202,    8],
       [2210,   11],
       [2276,   23],
       [2316,   25],
       [2498,   29]])

In [29]:
weight

array([2316, 1933, 1860, 2276, 2210, 2498, 2202, 1826, 2016, 1506])

In [30]:
mpg

array([ 6,  6, 11,  8, 23,  8,  7,  8, 29, 25])

In [31]:
weight.reshape(-1, 1)

array([[2316],
       [1933],
       [1860],
       [2276],
       [2210],
       [2498],
       [2202],
       [1826],
       [2016],
       [1506]])

In [32]:
mpg.reshape(-1, 1)

array([[ 6],
       [ 6],
       [11],
       [ 8],
       [23],
       [ 8],
       [ 7],
       [ 8],
       [29],
       [25]])

np.argsort(arr) -  index which represents array in sorted form

In [33]:
a = np.array([10, 50, 30, 20, 80, 40, 60])

In [34]:
np.argsort(a)

array([0, 3, 2, 5, 1, 6, 4], dtype=int64)

In [35]:
weight

array([2316, 1933, 1860, 2276, 2210, 2498, 2202, 1826, 2016, 1506])

In [36]:
mpg

array([ 6,  6, 11,  8, 23,  8,  7,  8, 29, 25])

In [37]:
ix = np.argsort(mpg)
print(ix)

[0 1 6 3 5 7 2 4 9 8]


In [38]:
weight[ix]

array([2316, 1933, 2202, 2276, 2498, 1826, 1860, 2210, 1506, 2016])

In [39]:
mpg[ix]

array([ 6,  6,  7,  8,  8,  8, 11, 23, 25, 29])

In [40]:
rel = np.concatenate(
    (weight[np.argsort(mpg)].reshape(-1, 1),
     mpg[np.argsort(mpg).reshape(-1, 1)]),
     axis = 1
)

In [41]:
print(rel)

[[2316    6]
 [1933    6]
 [2202    7]
 [2276    8]
 [2498    8]
 [1826    8]
 [1860   11]
 [2210   23]
 [1506   25]
 [2016   29]]


In [42]:
rel

array([[2316,    6],
       [1933,    6],
       [2202,    7],
       [2276,    8],
       [2498,    8],
       [1826,    8],
       [1860,   11],
       [2210,   23],
       [1506,   25],
       [2016,   29]])

In [43]:
np.argmax(mpg)  # gives the index of max milege

8

In [44]:
np.argmin(mpg)  # gives the index of min milege

0

In [45]:
mpg[2]

11

In [46]:
mpg[7]

8

In [47]:
# weight of car which is having heighest milege
weight[np.argmax(mpg)]

2016

### Pandas
    high level data preprocessing library of pyhton which is based on numpy arrays
    series -> 1D col vector / 1D array
    dataFrame -> 2D spread sheet like object / collection of series on axis - 1 logiaclly connected with indexed
    pannel -> 3D object which is collection of DataFrames

In [48]:
import pandas as pd

In [49]:
a1 = np.array([23, 45, 6, 7, 98, 90])
a1

array([23, 45,  6,  7, 98, 90])

In [50]:
s1 = pd.Series([35, 40, 50, 20, 25, 25, 70])

In [51]:
print(s1)

0    35
1    40
2    50
3    20
4    25
5    25
6    70
dtype: int64


In [52]:
s1[0]

35

In [53]:
s1[2]

50

'indexing and slicing in series'
    seriesloc[i] -> label indexes, series indexes
    series.iloc[i] ->default indexes 0 - n-1, array indexes 

In [54]:
s1.iloc[-1]  # can be used as normal indexing

70

In [73]:
s1.loc[0]  # can only be applied to the index which are avialable in the array

35

In [56]:
s2 = pd.Series([35, 40, 50, 20, 25, 25, 70], 
              name = "salary", 
              dtype = np.int32,
              index = ["sachin", "Tanvi", "Vijay", "sam", "simran", "Ravi", "Rajat"])  # indexing is not avialable in array
# Series is type of mapping func in java

In [57]:
s2

sachin    35
Tanvi     40
Vijay     50
sam       20
simran    25
Ravi      25
Rajat     70
Name: salary, dtype: int32

In [58]:
s1[1]  # numpy index

40

In [59]:
s1.iloc[1] # series index

40

In [60]:
s2["sam"]  # label(series) index(_we dont use this indexing_)

20

In [61]:
s2.loc["sam"]

20

In [62]:
s2["sachin":"simran"] # not recommended 

sachin    35
Tanvi     40
Vijay     50
sam       20
simran    25
Name: salary, dtype: int32

In [63]:
s2[0:4]  # numpy indexing

sachin    35
Tanvi     40
Vijay     50
sam       20
Name: salary, dtype: int32

In [64]:
s2.loc["sachin":"simran"]  # series indexing / lebel indexing

sachin    35
Tanvi     40
Vijay     50
sam       20
simran    25
Name: salary, dtype: int32

In [65]:
s2.index  # this gives only the index

Index(['sachin', 'Tanvi', 'Vijay', 'sam', 'simran', 'Ravi', 'Rajat'], dtype='object')

In [66]:
s2 + 20  # same as array operations

sachin    55
Tanvi     60
Vijay     70
sam       40
simran    45
Ravi      45
Rajat     90
Name: salary, dtype: int32

In [67]:
s3 = pd.Series([10, 15, 8, 5, 20, 5, 15],
              index = s2.index, name="hike", dtype = np.int32)

In [68]:
s2

sachin    35
Tanvi     40
Vijay     50
sam       20
simran    25
Ravi      25
Rajat     70
Name: salary, dtype: int32

In [69]:
s3

sachin    10
Tanvi     15
Vijay      8
sam        5
simran    20
Ravi       5
Rajat     15
Name: hike, dtype: int32

In [70]:
s2*(s3/100)

sachin     3.50
Tanvi      6.00
Vijay      4.00
sam        1.00
simran     5.00
Ravi       1.25
Rajat     10.50
dtype: float64

In [71]:
s2*(s3/100) + s2

sachin    38.50
Tanvi     46.00
Vijay     54.00
sam       21.00
simran    30.00
Ravi      26.25
Rajat     80.50
dtype: float64

In [74]:
s7 = pd.Series([35, 40, 50, 20, 25, 25, 70], 
              name = "salary", 
              dtype = np.int32,
              index = ["sachin", "Tanvi", "Vijay", "sam", "simran", "Ravi", "Rajat"])  # indexing is not avialable in array
# Series is type of mapping func in java

In [76]:
s7.loc["sachin"]

35

In [79]:
s7.loc["sam"]

20

In [77]:
s7.iloc[2]

50

In [78]:
s7

sachin    35
Tanvi     40
Vijay     50
sam       20
simran    25
Ravi      25
Rajat     70
Name: salary, dtype: int32